name: kirisawa CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.16.0
      - name: Install Dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm run typecheck
      - name: Build
        run: pnpm run build
